version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: consulta
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-app-network

  app:
    build: .
    restart: always
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/consulta
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - '8082:8082'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VUE_APP_PORT=8082
    networks:
      - my-app-network
    depends_on:
      - app

networks:
  my-app-network:
    driver: bridge
